### ISSUE TITLE
No reduce function to get length for MultiLineString

### ISSUE THREAD

**Issue by yauh** [tyrasd/geojson-length#1]
I'm using this module in a Meteor application and when I pass a MultiLineString to `geojson-length` I get an error message that there is no `reduce` method.

I took the MultiLineString example from http://geojsonlint.com/ for testing.

**Comment by tyrasd** [comment]
oops. :blush:
this is fixed with the `0.1.1` release on npm.

**Comment by yauh** [comment]
Excellent. I thought it was my brain letting me down again ;)
